"""
IVS-2025-Compliant Report Template

Defines the section structure required by International Valuation Standards
(IVS) January 2025.  Every report generated by GreenValue AI must follow
this structure to be accepted by banks and appraisal boards.

Reference: IVS-Jan-2025.pdf
  - IVS 101  Scope of Work
  - IVS 102  Investigations and Compliance
  - IVS 103  Reporting
  - IVS 104  Bases of Value (Market Value definition)
  - IVS 105  Valuation Approaches and Methods
"""

import logging
from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, List, Optional
from datetime import date

logger = logging.getLogger("greenvalue-report")


class IVSSection(str, Enum):
    """IVS-2025 report sections in mandatory order."""
    COVER = "cover"
    SCOPE_OF_WORK = "scope_of_work"              # IVS 101
    PROPERTY_DESCRIPTION = "property_description"
    MARKET_ANALYSIS = "market_analysis"
    VALUATION_APPROACHES = "valuation_approaches"  # IVS 105
    ENERGY_ASSESSMENT = "energy_assessment"         # GreenValue unique
    RENOVATION_IMPACT = "renovation_impact"         # GreenValue unique
    RECONCILIATION = "reconciliation"
    ASSUMPTIONS = "assumptions"                     # IVS 101 / 102
    APPENDIX_DETECTIONS = "appendix_detections"
    APPENDIX_FINANCIALS = "appendix_financials"
    APPENDIX_GLOSSARY = "appendix_glossary"
    APPENDIX_SOURCES = "appendix_sources"


@dataclass
class IVSCoverData:
    """Data for the cover page."""
    property_address: str = ""
    property_photo_path: Optional[str] = None
    heatmap_path: Optional[str] = None
    report_date: str = field(default_factory=lambda: date.today().isoformat())
    valuation_date: str = field(default_factory=lambda: date.today().isoformat())
    appraiser_name: str = "GreenValue AI Automated Valuation"
    report_number: str = ""
    client_name: str = ""
    intended_use: str = "Mortgage lending, investment decision support"


@dataclass
class IVSScopeOfWork:
    """IVS 101 — Scope of Work section data."""
    purpose: str = "To estimate Market Value as defined by IVS 104"
    intended_use: str = "Mortgage lending, investment decision support, energy retrofit planning"
    type_of_value: str = "Market Value (IVS 104)"
    valuation_date: str = field(default_factory=lambda: date.today().isoformat())
    inspection_date: str = field(default_factory=lambda: date.today().isoformat())
    inspection_type: str = "Exterior visual inspection via photographic analysis (YOLO11 AI-assisted)"
    assumptions: List[str] = field(default_factory=lambda: [
        "The property is free of encumbrances unless otherwise stated.",
        "Building components visible in photographs are representative of overall condition.",
        "Energy performance estimates are based on AI-detected building components and standard thermal models.",
        "Cost estimates are derived from published industry benchmarks and may vary by region.",
    ])
    special_assumptions: List[str] = field(default_factory=list)
    departures_from_ivs: List[str] = field(default_factory=lambda: [
        "Physical inspection limited to photographic analysis; interior not inspected.",
        "Market data derived from knowledge base rather than direct market survey.",
    ])


@dataclass
class PropertyDescription:
    """Property characteristics for Section 2."""
    property_id: str = ""
    address: str = ""
    property_type: str = "Residential"
    building_year: Optional[int] = None
    area_sqm: Optional[float] = None
    num_floors: Optional[int] = None
    zoning: str = ""
    detected_components: List[Dict] = field(default_factory=list)
    # Each component: {type, condition, u_value, area, confidence}


@dataclass
class ComparableProperty:
    """A comparable sale used in the Sales Comparison Approach."""
    address: str = ""
    sale_date: str = ""
    sale_price: float = 0.0
    area_sqm: float = 0.0
    price_per_sqm: float = 0.0
    energy_label: str = ""
    similarity_score: float = 0.0   # 0.0–1.0 from Qdrant
    adjustments: List[Dict] = field(default_factory=list)
    # Each: {type, amount, reason}
    adjusted_price: float = 0.0


@dataclass
class MarketAnalysis:
    """Section 3 — Market conditions and comparable data."""
    market_area: str = ""              # e.g. "Amsterdam, Noord-Holland"
    analysis_date: str = field(default_factory=lambda: date.today().isoformat())
    median_price_sqm: float = 0.0
    price_trend_pct: float = 0.0       # year-over-year % change
    avg_days_on_market: int = 0
    inventory_level: str = ""           # "Low", "Balanced", "High"
    energy_premium_pct: float = 0.0    # % premium for labels A/B vs E/F/G
    comparable_properties: List[ComparableProperty] = field(default_factory=list)
    market_narrative: str = ""
    data_source_notes: List[str] = field(default_factory=list)


@dataclass
class ValuationApproach:
    """One of the three IVS 105 valuation approaches."""
    approach_name: str = ""          # "Cost", "Sales Comparison", "Income"
    applicable: bool = True
    value_estimate: Optional[float] = None
    methodology: str = ""
    data_sources: List[str] = field(default_factory=list)
    adjustments: List[Dict] = field(default_factory=list)
    weight_in_reconciliation: float = 0.0  # 0.0 – 1.0
    book_reference: str = ""         # Which book this came from


@dataclass
class EnergyAssessment:
    """Section 5 — GreenValue AI unique energy assessment."""
    energy_label_current: str = ""   # A through G
    energy_label_projected: str = "" # After upgrades
    total_heat_loss_kwh: float = 0.0
    carbon_footprint_kg: float = 0.0
    component_u_values: List[Dict] = field(default_factory=list)
    # Each: {component, u_value_current, u_value_target, condition, area_sqm}
    heatmap_path: Optional[str] = None


@dataclass
class UpgradeRecommendation:
    """A single renovation upgrade recommendation."""
    component: str = ""              # "roof_insulation", "window_replacement", etc.
    description: str = ""
    estimated_cost: float = 0.0
    estimated_value_add: float = 0.0
    roi_percent: float = 0.0
    payback_years: float = 0.0
    energy_savings_kwh: float = 0.0
    co2_reduction_kg: float = 0.0
    energy_label_impact: str = ""    # e.g. "D → B"
    cost_source: str = ""            # Book reference
    finance_source: str = ""         # Book reference
    valuation_method: str = ""       # "Income Approach (Cap Rate 6%)"


@dataclass
class RenovationImpact:
    """Section 6 — GreenValue AI unique renovation impact analysis."""
    upgrades: List[UpgradeRecommendation] = field(default_factory=list)
    total_cost: float = 0.0
    total_value_add: float = 0.0
    aggregate_roi: float = 0.0
    aggregate_payback_years: float = 0.0
    before_label: str = ""
    after_label: str = ""


@dataclass
class Reconciliation:
    """Section 7 — Final value opinion."""
    cost_approach_value: Optional[float] = None
    sales_comparison_value: Optional[float] = None
    income_approach_value: Optional[float] = None
    reconciled_value: float = 0.0
    reconciliation_narrative: str = ""
    confidence_level: str = "High"   # High, Moderate, Low
    green_premium_amount: float = 0.0
    green_premium_basis: str = ""    # IVS legal reference


@dataclass
class IVSReportData:
    """Complete data model for an IVS-2025-compliant report."""
    cover: IVSCoverData = field(default_factory=IVSCoverData)
    scope: IVSScopeOfWork = field(default_factory=IVSScopeOfWork)
    property_desc: PropertyDescription = field(default_factory=PropertyDescription)
    market: MarketAnalysis = field(default_factory=MarketAnalysis)
    valuation_approaches: List[ValuationApproach] = field(default_factory=list)
    energy: EnergyAssessment = field(default_factory=EnergyAssessment)
    renovation: RenovationImpact = field(default_factory=RenovationImpact)
    reconciliation: Reconciliation = field(default_factory=Reconciliation)
    glossary_terms: List[Dict] = field(default_factory=list)
    data_sources: List[Dict] = field(default_factory=list)
    # Each source: {book_id, title, section_cited, chapter}

    def validate_ivs_compliance(self) -> List[str]:
        """
        Validate that all IVS-2025 mandatory fields are present.
        Returns list of compliance warnings (empty = fully compliant).
        """
        warnings = []

        # IVS 101 — Scope of Work
        if not self.scope.purpose:
            warnings.append("IVS 101: Purpose of valuation is required")
        if not self.scope.type_of_value:
            warnings.append("IVS 101: Type of value must be stated")
        if not self.scope.valuation_date:
            warnings.append("IVS 101: Valuation date is required")

        # IVS 102 — Investigations
        if not self.scope.assumptions:
            warnings.append("IVS 102: Assumptions must be stated")

        # IVS 103 — Reporting
        if not self.cover.appraiser_name:
            warnings.append("IVS 103: Appraiser identity is required")
        if not self.cover.report_date:
            warnings.append("IVS 103: Report date is required")

        # IVS 104 — Market Value
        if self.reconciliation.reconciled_value <= 0:
            warnings.append("IVS 104: Final value opinion is required")

        # IVS 105 — At least one approach must be applied
        applied = [a for a in self.valuation_approaches if a.applicable and a.value_estimate]
        if not applied:
            warnings.append("IVS 105: At least one valuation approach must be applied")

        # Reconciliation weights should sum to ~1.0
        weight_sum = sum(a.weight_in_reconciliation for a in self.valuation_approaches if a.applicable)
        if applied and abs(weight_sum - 1.0) > 0.05:
            warnings.append(f"IVS 105: Approach weights sum to {weight_sum:.2f}, should be ~1.0")

        return warnings


class IVSTemplate:
    """
    IVS-2025-compliant report template.

    Provides the ordered section structure and compliance rules.
    Ensures every generated report passes institutional review.
    """

    # Mandatory sections in IVS order
    SECTION_ORDER = [
        IVSSection.COVER,
        IVSSection.SCOPE_OF_WORK,
        IVSSection.PROPERTY_DESCRIPTION,
        IVSSection.MARKET_ANALYSIS,
        IVSSection.VALUATION_APPROACHES,
        IVSSection.ENERGY_ASSESSMENT,
        IVSSection.RENOVATION_IMPACT,
        IVSSection.RECONCILIATION,
        IVSSection.ASSUMPTIONS,
        IVSSection.APPENDIX_DETECTIONS,
        IVSSection.APPENDIX_FINANCIALS,
        IVSSection.APPENDIX_GLOSSARY,
        IVSSection.APPENDIX_SOURCES,
    ]

    # Section titles by language
    SECTION_TITLES = {
        "en": {
            IVSSection.COVER: "Valuation Report",
            IVSSection.SCOPE_OF_WORK: "1. Scope of Work",
            IVSSection.PROPERTY_DESCRIPTION: "2. Property Description",
            IVSSection.MARKET_ANALYSIS: "3. Market Analysis",
            IVSSection.VALUATION_APPROACHES: "4. Valuation Approaches",
            IVSSection.ENERGY_ASSESSMENT: "5. Energy & Sustainability Assessment",
            IVSSection.RENOVATION_IMPACT: "6. Renovation Impact Analysis",
            IVSSection.RECONCILIATION: "7. Reconciliation & Final Value Opinion",
            IVSSection.ASSUMPTIONS: "8. Assumptions & Limiting Conditions",
            IVSSection.APPENDIX_DETECTIONS: "Appendix A — AI Detection Results",
            IVSSection.APPENDIX_FINANCIALS: "Appendix B — Financial Calculations",
            IVSSection.APPENDIX_GLOSSARY: "Appendix C — Glossary of Terms",
            IVSSection.APPENDIX_SOURCES: "Appendix D — Data Sources & Citations",
        },
        "tr": {
            IVSSection.COVER: "Değerleme Raporu",
            IVSSection.SCOPE_OF_WORK: "1. Çalışmanın Kapsamı",
            IVSSection.PROPERTY_DESCRIPTION: "2. Gayrimenkul Tanımı",
            IVSSection.MARKET_ANALYSIS: "3. Piyasa Analizi",
            IVSSection.VALUATION_APPROACHES: "4. Değerleme Yaklaşımları",
            IVSSection.ENERGY_ASSESSMENT: "5. Enerji ve Sürdürülebilirlik Değerlendirmesi",
            IVSSection.RENOVATION_IMPACT: "6. Renovasyon Etki Analizi",
            IVSSection.RECONCILIATION: "7. Uzlaştırma ve Nihai Değer Görüşü",
            IVSSection.ASSUMPTIONS: "8. Varsayımlar ve Sınırlayıcı Koşullar",
            IVSSection.APPENDIX_DETECTIONS: "Ek A — AI Tespit Sonuçları",
            IVSSection.APPENDIX_FINANCIALS: "Ek B — Finansal Hesaplamalar",
            IVSSection.APPENDIX_GLOSSARY: "Ek C — Terimler Sözlüğü",
            IVSSection.APPENDIX_SOURCES: "Ek D — Veri Kaynakları ve Referanslar",
        },
        "de": {
            IVSSection.COVER: "Bewertungsbericht",
            IVSSection.SCOPE_OF_WORK: "1. Auftragsumfang",
            IVSSection.PROPERTY_DESCRIPTION: "2. Objektbeschreibung",
            IVSSection.MARKET_ANALYSIS: "3. Marktanalyse",
            IVSSection.VALUATION_APPROACHES: "4. Bewertungsverfahren",
            IVSSection.ENERGY_ASSESSMENT: "5. Energie- und Nachhaltigkeitsbewertung",
            IVSSection.RENOVATION_IMPACT: "6. Sanierungswirkungsanalyse",
            IVSSection.RECONCILIATION: "7. Abstimmung und endgültige Wertermittlung",
            IVSSection.ASSUMPTIONS: "8. Annahmen und einschränkende Bedingungen",
            IVSSection.APPENDIX_DETECTIONS: "Anlage A — KI-Erkennungsergebnisse",
            IVSSection.APPENDIX_FINANCIALS: "Anlage B — Finanzberechnungen",
            IVSSection.APPENDIX_GLOSSARY: "Anlage C — Glossar",
            IVSSection.APPENDIX_SOURCES: "Anlage D — Datenquellen und Zitate",
        },
    }

    @classmethod
    def get_section_title(cls, section: IVSSection, language: str = "en") -> str:
        """Get localized section title."""
        lang_titles = cls.SECTION_TITLES.get(language, cls.SECTION_TITLES["en"])
        return lang_titles.get(section, section.value)

    @classmethod
    def get_ordered_sections(cls) -> List[IVSSection]:
        """Return sections in mandatory IVS order."""
        return list(cls.SECTION_ORDER)

    @classmethod
    def build_empty_report(
        cls,
        property_id: str,
        address: str = "",
        report_number: str = "",
    ) -> IVSReportData:
        """
        Create an empty IVS report data structure with defaults.
        Populate and pass to ReportEngine.render() to generate PDF.
        """
        report = IVSReportData()
        report.cover.property_address = address
        report.cover.report_number = report_number
        report.property_desc.property_id = property_id
        report.property_desc.address = address

        # Default three valuation approaches (IVS 105)
        report.valuation_approaches = [
            ValuationApproach(
                approach_name="Cost Approach",
                book_reference="The Appraisal of Real Estate, 15th Ed. — Chapter 17",
            ),
            ValuationApproach(
                approach_name="Sales Comparison Approach",
                book_reference="The Appraisal of Real Estate, 15th Ed. — Chapter 14",
            ),
            ValuationApproach(
                approach_name="Income Approach",
                book_reference=(
                    "The Appraisal of Real Estate, 15th Ed. — Chapter 20; "
                    "What Every RE Investor Needs to Know — Cap Rate / NOI"
                ),
            ),
        ]

        return report
